#!/bin/sh -ue

# Configuration values are taken from the environment, and if they are missing
# default values are used
NODM_XINIT=${NODM_XINIT:-"/usr/bin/xinit"}
NODM_XSESSION=${NODM_XSESSION:-"/etc/X11/Xsession"}
NODM_X_OPTIONS=${NODM_X_OPTIONS:-"vt7 -nolisten tcp"}
NODM_USER=${NODM_USER:-"root"}
NODM_MIN_SESSION_TIME=${NODM_MIN_SESSION_TIME:-"10"}

# Run an X session, returning success if it lasted at least
# $NODM_MIN_SESSION_TIME
run()
{
	start=`date +%s`
	/usr/lib/nodm/pam-helper
	end=`date +%s`
	if [ `expr $end - $start` -ge $NODM_MIN_SESSION_TIME ]
	then
		return 0
	else
		return 1
	fi
}

while :
do
	if ! run
	then
		exit 1
	fi
done

exit 0
