#!/bin/sh

case "$1" in
	'')
#		test "$2" != "a" && echo "\$3 is '$2' instead of 'a'"
#		test "$3" != "b" && echo "\$4 is '$3' instead of 'b'"
#		test "$4" != "c" && echo "\$5 is '$4' instead of 'c'"
		echo "PATH is: $PATH"
		echo "USER is: $USER"
		echo "HOME is: $HOME"
		echo "pwd: `pwd`"
		echo "id: `id`"
		pstree `pgrep nodm|head -1`
#		set > test_nodm.env.tmp
		exit 0
		;;
	*)
		export NODM_USER=$1
		export NODM_XINIT="time"
		export NODM_XSESSION="`pwd`/$0"
#		export NODM_X_OPTIONS="runtest a b c"
		export NODM_MIN_SESSION_TIME=60
		exec ./nodm --session `pwd`/nodm
		;;
#	'')
#		echo "Use: $0 username" >&2
#		exit 1
#		;;
esac
